CREATE TABLE Note(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      varchar(255) NOT NULL,
    text       text         NOT NULL,
    author     varchar(255) NOT NULL,
    created_at timestamptz  NOT NULL,
    updated_at timestamptz  NOT NULL,
    version    bigint       NOT NULL
)