CREATE TABLE note_revision(
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id    bigint REFERENCES note (id) ON DELETE CASCADE,
    old_title  varchar(255) NOT NULL,
    old_text   text         NOT NULL,
    changed_at timestamptz  NOT NULL
)