spring:
  data:
    mongodb:
      uri: "mongodb://${MONGO_DB_HOST}:${MONGO_DB_PORT}/${MONGO_DB_NAME}"
  application:
    name: spring
  profiles:
    active: dev
  datasource:
    url: "jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration/postgres
    validate-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      acks: all
      properties:
        enable.idempotence: true

      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: note_event_log
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: "org.springframework.kafka.support.serializer.JsonDeserializer"
        spring.json.trusted.packages: "com.practice.spring.event"
        spring.json.value.default.type: "com.practice.spring.event.NoteEvent"

clickhouse:
  url: "jdbc:clickhouse://localhost:8123/${CLICKHOUSE_DB}"
  driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
  username: ${CLICKHOUSE_USER}
  password: ${CLICKHOUSE_PASSWORD}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - metrics
          - info

logging:
  level:
    org.hibernate.sql: debug

import:
  note:
    limit: 2

jwt:
  jwt-secret-key: ${JWT_SECRET}
  issuer: app-name
  leeway-seconds: 30
  access-token-duration: PT15M