spring:
  application:
    name: spring
  profiles:
    active: prod


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
          - metrics
          - info