CREATE TABLE note_event_log
(
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id     bigint       NOT NULL,
    author      varchar(250) NOT NULL,
    event_id    uuid         NOT NULL UNIQUE,
    type        varchar(50)  NOT NULL,
    occurred_at timestamptz  NOT NULL,
    received_at timestamptz  NOT NULL
)