package com.practice.spring.error;

public enum ErrorType {
    VALIDATION_ERROR, NOTE_NOT_FOUND_ERROR, AUTHOR_NOT_FOUND_ERROR, NOTE_LIMIT_ERROR, UNSUPPORTED_EXPORT_NOTE_FORMAT_ERROR,
    ILLEGAL_EXPORT_NOTE_FORMAT_ERROR, PARSE_NOTE_ERROR, IMPORT_NOTES_ERROR, OPTIMISTIC_LOCKING_ERROR;
}
